version: '3.3'

services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Server
      - SERVER_URL=http://localhost:8080
      - SERVER_PORT=8080
      
      # Cors
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      
      # Log
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS
      - LOG_COLOR=true
      
      # Database (usando in-memory por enquanto)
      - DATABASE_ENABLED=false
      
      # Authentication
      - AUTHENTICATION_API_KEY=pange-bot-secret-key-2024
      
      # Webhook
      - WEBHOOK_GLOBAL_ENABLED=false
      - WEBHOOK_BY_EVENTS=true
      
      # QR Code
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#198754
      
      # Instance
      - DEL_INSTANCE=false
      
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  evolution_instances:
  evolution_store:



